### ISSUE TITLE
Wrong tskit URL

### ISSUE THREAD

**Issue by hyanwong** [conda-forge/tskit-feedstock#4]
README.md has 

> Home: http://github.com/tskit/tskit

which should be 

> Home: http://github.com/tskit-dev/tskit

**Comment by jeromekelleher** [comment]
Good spot, thanks. The metadata is in ``recipe/meta.yml`` if you'd like to open a PR.

**Comment by hyanwong** [comment]
Since I don't have a clone of this repo, I wondered if it might not be easier for you to make a simple change like this (hence not submitting this as a PR)

**Comment by jeromekelleher** [comment]
OK, I'll queue it up for the next time I'm changing it.
